/* tslint:disable */
/* eslint-disable */
/**
 * zkNFT API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface MintPostRequest
 */
export interface MintPostRequest {
    /**
     * 
     * @type {string}
     * @memberof MintPostRequest
     */
    'recipient': string;
}
/**
 * 
 * @export
 * @interface StakePost200Response
 */
export interface StakePost200Response {
    /**
     * Base64 encoded serialized Solana transaction
     * @type {string}
     * @memberof StakePost200Response
     */
    'base64EncodedTransaction': string;
    /**
     * 
     * @type {string}
     * @memberof StakePost200Response
     */
    'blockhash': string;
    /**
     * 
     * @type {number}
     * @memberof StakePost200Response
     */
    'lastValidBlockHeight': number;
}
/**
 * 
 * @export
 * @interface StakePostRequest
 */
export interface StakePostRequest {
    /**
     * 
     * @type {string}
     * @memberof StakePostRequest
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof StakePostRequest
     */
    'assetId': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Mint zkNFT
         * @param {MintPostRequest} [mintPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mintPost: async (mintPostRequest?: MintPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mint`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(mintPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stakePost: async (stakePostRequest?: StakePostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stake`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stakePostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unstake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unstakePost: async (stakePostRequest?: StakePostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/unstake`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stakePostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Mint zkNFT
         * @param {MintPostRequest} [mintPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mintPost(mintPostRequest?: MintPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StakePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.mintPost(mintPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.mintPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StakePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stakePost(stakePostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.stakePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unstake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unstakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StakePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unstakePost(stakePostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.unstakePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Mint zkNFT
         * @param {MintPostRequest} [mintPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mintPost(mintPostRequest?: MintPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<StakePost200Response> {
            return localVarFp.mintPost(mintPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Stake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<StakePost200Response> {
            return localVarFp.stakePost(stakePostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unstake zkNFT
         * @param {StakePostRequest} [stakePostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unstakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<StakePost200Response> {
            return localVarFp.unstakePost(stakePostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Mint zkNFT
     * @param {MintPostRequest} [mintPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public mintPost(mintPostRequest?: MintPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).mintPost(mintPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stake zkNFT
     * @param {StakePostRequest} [stakePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public stakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).stakePost(stakePostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unstake zkNFT
     * @param {StakePostRequest} [stakePostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public unstakePost(stakePostRequest?: StakePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).unstakePost(stakePostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



