name = "zk-nft-api"
main = "src/index.ts"
compatibility_date = "2024-10-07"
compatibility_flags = [ "nodejs_compat" ]

[[unsafe.bindings]]
name = "MINT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 3, period = 60 }

[[unsafe.bindings]]
name = "STAKE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 2, period = 10 }

[[d1_databases]]
binding = "DB"
database_name = "zk-nft-archetype-dev"
database_id = "9da3c9e8-82d7-4aa0-874d-d99ba86705f1"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"`
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
